---
# Recipe to encrypt external volume

- name: Copy indigo-dc.galaxycloud-os scripts
  template: src={{ item.script }} dest={{ item.destination }} mode=a+x
  with_items:
    - { script: 'fast_luks.j2', destination: '/usr/local/bin/fast_luks' }
    - { script: 'luksctl.j2', destination: '/usr/local/bin/luksctl' }
  become_user: root
  become_method: sudo

- include: sendmail.yml

- name: Wait for fast_luks pidfile creation
  wait_for:
    path: /var/run/fast_luks/fast_luks.pid
    timeout: 86400 # wait 24 hous FIXME

- name: Wait for fast_luks finish (pidfile deletion)
  wait_for:
    path: /var/run/fast_luks/fast_luks.pid
    state: absent
    timeout: 86400 # wait 24 hours FIXME

- name: Check /etc/luks-cryptdev.conf. If not there something went wrong.
  wait_for:
    path: /etc/luks-cryptdev.conf
    state: present

- name: Set permissions to {{ export_dir }} directory
  file: path={{ export_dir }}
        state=directory
        owner={{ galaxy_user }}
        group={{ galaxy_user }}
  become_user: root
  become_method: sudo

