---
# Prerequisites installation recipe
# Install CentOS 7 and Ubuntu 14.04 dependencies, creates directories, logrotate and password generator installation.

#---
#CentOS 7

- name: Install CentOS7 packages
  yum: name={{item}}
       state=present
  with_items:
    - git
    - vim
    - wget
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Install the 'Development tools' package group
  yum: name="@Development tools"
       state=present
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#---
# Ubuntu 14.04

- name: Install Ubuntu packages
  apt: name={{item}}
       state=present
  with_items:
    - git
    - vim
    - wget
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"


#########################################################
# Create directories

- name: Create log directory
  file: path={{galaxy_log_path}}
        state=directory
        owner={{galaxy_user}}
        group={{galaxy_user}}
  become_user: root
  become_method: sudo

- name: Create export directory
  file: path={{export_dir}}
        state=directory
        owner={{galaxy_user}}
        group={{galaxy_user}}
  become_user: root
  become_method: sudo

- name: Create /etc/galaxy directory
  file: path=/etc/galaxy
        state=directory
        owner={{galaxy_user}}
        group={{galaxy_user}}
  become_user: root
  become_method: sudo
